// <auto-generated />
using System;
using Estufa.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Estufa.Migrations
{
    [DbContext(typeof(EstufaContext))]
    [Migration("20241114165217_Deploytwo")]
    partial class Deploytwo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("Estufa.Models.Bomba", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastActivation")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantidade")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Bomba");
                });

            modelBuilder.Entity("Estufa.Models.Lampada", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UltimaAtivacao")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Lampada");
                });

            modelBuilder.Entity("Estufa.Models.Login", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Login");
                });

            modelBuilder.Entity("Estufa.Models.Temperatura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("TemperaturaAtual")
                        .HasColumnType("REAL");

                    b.Property<double>("TemperaturaIdeal")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("UltimaMedicao")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Temperatura");
                });

            modelBuilder.Entity("Estufa.Models.Umidade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UltimaMedicao")
                        .HasColumnType("TEXT");

                    b.Property<double>("UmidadeAtual")
                        .HasColumnType("REAL");

                    b.Property<double>("UmidadeIdeal")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Umidade");
                });

            modelBuilder.Entity("Estufa.Models.UmidadeTerra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UltimaMedicao")
                        .HasColumnType("TEXT");

                    b.Property<double>("UmidadeTerraAtual")
                        .HasColumnType("REAL");

                    b.Property<double>("UmidadeTerraIdeal")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("UmidadeTerra");
                });
#pragma warning restore 612, 618
        }
    }
}
